version: '3.7'
services:

  app:
    build:
      context: .
    image: app:dev
    volumes:
      - .:/opt/app
      - bundler_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    command: bundle exec rails server -b '0.0.0.0'
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=password
    stdin_open: true
    tty: true
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  bundler_cache:
    driver: local
